# Generated by Django 4.2.11 on 2024-04-24 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homophone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homophone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('video_link', models.URLField()),
                ('video_duration', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('start_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('end_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('word_duration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('difficulty', models.CharField(default='empty', max_length=7)),
                ('positive', models.BooleanField(default=False)),
                ('negative', models.BooleanField(default=False)),
                ('pos_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lipReadingDataset.partofspeach')),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lipReadingDataset.textdata')),
            ],
        ),
        migrations.CreateModel(
            name='WordHomophone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homophones_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lipReadingDataset.homophone')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lipReadingDataset.worddetail')),
            ],
        ),
    ]
