# Generated by Django 4.2.11 on 2024-04-15 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homophone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('difficulty', models.CharField(max_length=7)),
                ('positive', models.BooleanField()),
                ('negative', models.BooleanField()),
                ('pos_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lipReadingDataset.partofspeach')),
            ],
        ),
        migrations.RemoveField(
            model_name='worddetails',
            name='text_id',
        ),
        migrations.RemoveField(
            model_name='textdata',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='textdata',
            name='race',
        ),
        migrations.DeleteModel(
            name='VideoData',
        ),
        migrations.DeleteModel(
            name='WordDetails',
        ),
        migrations.AddField(
            model_name='worddetail',
            name='text_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lipReadingDataset.textdata'),
        ),
        migrations.AddField(
            model_name='homephone',
            name='word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lipReadingDataset.worddetail'),
        ),
    ]
