# Generated by Django 4.2.11 on 2024-04-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worddetail',
            old_name='pos_id',
            new_name='pos',
        ),
        migrations.RenameField(
            model_name='worddetail',
            old_name='text_id',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='wordhomophone',
            old_name='homophones_id',
            new_name='homophones',
        ),
        migrations.RenameField(
            model_name='wordhomophone',
            old_name='word_id',
            new_name='word',
        ),
    ]
