# Generated by Django 4.2.11 on 2024-04-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0002_rename_pos_id_worddetail_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homophone',
            name='homophone_group_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
