# Generated by Django 4.2.11 on 2024-04-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0002_homephone_partofspeach_worddetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='video_duration',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AddField(
            model_name='textdata',
            name='video_link',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='worddetail',
            name='word_duration',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
