# Generated by Django 4.2.11 on 2024-04-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0003_homophone_homophone_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddetail',
            name='homophone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lipReadingDataset.homophone'),
        ),
        migrations.DeleteModel(
            name='WordHomophone',
        ),
    ]
