# Generated by Django 4.2.11 on 2024-04-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0003_textdata_video_duration_textdata_video_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddetail',
            name='difficulty',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='worddetail',
            name='end_time',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='worddetail',
            name='negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worddetail',
            name='positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worddetail',
            name='start_time',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
