# Generated by Django 4.2.11 on 2024-04-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0004_worddetail_homophone_delete_wordhomophone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddetail',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lipReadingDataset.partofspeach'),
        ),
    ]
