# Generated by Django 4.2.11 on 2024-04-19 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0004_alter_worddetail_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddetail',
            name='pos_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='lipReadingDataset.partofspeach'),
        ),
    ]
