# Generated by Django 4.2.11 on 2024-04-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0005_alter_worddetail_pos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddetail',
            name='difficulty',
            field=models.CharField(default='unknown', max_length=7),
        ),
    ]
