# Generated by Django 4.2.11 on 2024-04-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0006_alter_worddetail_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddetail',
            name='difficulty',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
