# Generated by Django 4.2.11 on 2024-04-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0008_alter_worddetail_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worddetail',
            name='difficulty',
        ),
    ]
