# Generated by Django 4.2.11 on 2024-04-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0009_remove_worddetail_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddetail',
            name='difficulty',
            field=models.CharField(default='empty', max_length=7),
        ),
    ]
