# Generated by Django 4.2.11 on 2024-04-19 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0010_worddetail_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddetail',
            name='pos_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lipReadingDataset.partofspeach'),
        ),
        migrations.AlterField(
            model_name='worddetail',
            name='text_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lipReadingDataset.textdata'),
        ),
    ]
