# Generated by Django 4.2.11 on 2024-04-19 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lipReadingDataset', '0011_alter_worddetail_pos_id_alter_worddetail_text_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddetail',
            name='pos_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lipReadingDataset.partofspeach'),
        ),
    ]
